// This file is auto-generated by @hey-api/openapi-ts

/**
 * CountryInfo Dto
 */
export type CountryInfoDto = {
    /**
     * CommonName
     */
    commonName: (string) | null;
    /**
     * OfficialName
     */
    officialName: (string) | null;
    /**
     * CountryCode
     */
    countryCode: (string) | null;
    /**
     * Region
     */
    region: (string) | null;
    /**
     * Country Borders
     */
    borders?: Array<CountryInfoDto> | null;
};

/**
 * Country
 */
export type CountryV3Dto = {
    countryCode: (string) | null;
    name: (string) | null;
};

export type HolidayTypes = 'Public' | 'Bank' | 'School' | 'Authorities' | 'Optional' | 'Observance';

/**
 * Long Weekend
 */
export type LongWeekendV3Dto = {
    /**
     * StartDate
     */
    startDate?: string;
    /**
     * EndDate
     */
    endDate?: string;
    /**
     * DayCount
     */
    dayCount?: number;
    /**
     * NeedBridgeDay
     */
    needBridgeDay?: boolean;
};

/**
 * Public Holiday
 */
export type PublicHolidayV3Dto = {
    /**
     * The date
     */
    date?: string;
    /**
     * Local name
     */
    localName: (string) | null;
    /**
     * English name
     */
    name: (string) | null;
    /**
     * ISO 3166-1 alpha-2
     */
    countryCode: (string) | null;
    /**
     * Is this public holiday every year on the same date
     * @deprecated
     */
    fixed?: boolean;
    /**
     * Is this public holiday in every county (federal state)
     */
    global?: boolean;
    /**
     * ISO-3166-2 - Federal states
     */
    counties?: Array<(string)> | null;
    /**
     * The launch year of the public holiday
     */
    launchYear?: (number) | null;
    /**
     * A list of types the public holiday it is valid
     */
    types: Array<HolidayTypes> | null;
};

/**
 * Version Info Dto
 */
export type VersionInfoDto = {
    /**
     * Name
     */
    name: (string) | null;
    /**
     * Version
     */
    version: (string) | null;
};

export type CountryCountryInfoData = {
    path: {
        countryCode: string;
    };
};

export type CountryCountryInfoResponse = (CountryInfoDto);

export type CountryCountryInfoError = unknown;

export type CountryAvailableCountriesResponse = (Array<CountryV3Dto>);

export type CountryAvailableCountriesError = unknown;

export type LongWeekendLongWeekendData = {
    path: {
        countryCode: string;
        year: number;
    };
};

export type LongWeekendLongWeekendResponse = (Array<LongWeekendV3Dto>);

export type LongWeekendLongWeekendError = unknown;

export type PublicHolidayPublicHolidaysV3Data = {
    path: {
        countryCode: string;
        year: number;
    };
};

export type PublicHolidayPublicHolidaysV3Response = (Array<PublicHolidayV3Dto>);

export type PublicHolidayPublicHolidaysV3Error = (unknown);

export type PublicHolidayIsTodayPublicHolidayData = {
    path: {
        /**
         * The Country Code
         */
        countryCode: string;
    };
    query?: {
        /**
         * Federal State Code
         */
        countyCode?: string;
        /**
         * utc timezone offset
         */
        offset?: number;
    };
};

export type PublicHolidayIsTodayPublicHolidayResponse = (unknown | void);

export type PublicHolidayIsTodayPublicHolidayError = (unknown);

export type PublicHolidayNextPublicHolidaysData = {
    path: {
        countryCode: string;
    };
};

export type PublicHolidayNextPublicHolidaysResponse = (Array<PublicHolidayV3Dto>);

export type PublicHolidayNextPublicHolidaysError = unknown;

export type PublicHolidayNextPublicHolidaysWorldwideResponse = (Array<PublicHolidayV3Dto>);

export type PublicHolidayNextPublicHolidaysWorldwideError = unknown;

export type VersionGetVersionResponse = (VersionInfoDto);

export type VersionGetVersionError = unknown;